# https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-bicep
name: user-service
properties:
  configuration:
    ingress:
      external: false
      targetPort: 8085
    dapr:
      appId: userservice
      enabled: true
      appPort: 8085
  template:
    containers:
      - image: docker.io/michalmoudry/user-service:latest
        name: user-service