name: user-service
type: Microsoft.App/containerApps
tags:
  system: mrf
properties:
  environmentId: /subscriptions/d2fb5eac-1786-4f84-b0df-14c3cc71a88f/resourceGroups/microservice-reference-framework/providers/Microsoft.App/managedEnvironments/microservice-ref-framework-env
  configuration:
    ingress:
      external: true
      targetPort: 8085
      allowInsecure: true
  template:
    containers:
      - image: docker.io/michalmoudry/user-service:latest
        name: user-service
# https://learn.microsoft.com/en-au/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#container-app-examples