name: user-service
type: Microsoft.App/containerApps
tags:
  system: mrf
properties:
  environmentId: /subscriptions/[subscription_id]/resourceGroups/microservice-reference-framework/providers/Microsoft.App/managedEnvironments/microservice-ref-framework-env
  configuration:
    ingress:
      external: true
      targetPort: 8085
      allowInsecure: true
  template:
    containers:
      - image: docker.io/michalmoudry/user-service:latest
        name: user-service
        env:
          - name: FB_TYPE
            value: [FB_TYPE]
          - name: FB_PRIV_KEY_ID
            value: [FB_PRIV_KEY_ID]
          - name: PRIVATE_KEY
            value: [PRIVATE_KEY]
          - name: FB_CLIENT_EMAIL
            value: [FB_CLIENT_EMAIL]
          - name: FB_CLIENT_ID
            value: [FB_CLIENT_ID]
          - name: FB_CLIENT_CERT_URL
            value: [FB_CLIENT_CERT_URL]
# https://learn.microsoft.com/en-au/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#container-app-examples