name: user-service
location: "East US 2"
properties:
  environmentId: /subscriptions/[subscription_id]/resourceGroups/microservice-reference-framework/providers/Microsoft.App/managedEnvironments/microservice-ref-framework-env
  configuration:
    dapr:
      appId: userservice
      enabled: true
      appPort: 8085
# https://learn.microsoft.com/en-au/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#container-app-examples