# https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-bicep
name: user-service
# d2fb5eac-1786-4f84-b0df-14c3cc71a88f
properties:
  environmentId: /subscriptions/[subscription_id]/resourceGroups/microservice-reference-framework/providers/Microsoft.App/managedEnvironments/microservice-ref-framework-env
  configuration:
    ingress:
      external: false
      targetPort: 8085
    dapr:
      appId: userservice
      enabled: true
      appPort: 8085
  template:
    containers:
      - image: docker.io/michalmoudry/user-service:latest
        name: user-service