apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mrf_pub_sub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
scopes:
  - userservice
  - workflowservice